// Mocks generated by Mockito 5.3.2 from annotations
// in repo_search/test/features/github_repo/ui/search_settings_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:repo_search/features/github_repo/data/search_settings_repository.dart'
    as _i2;
import 'package:repo_search/features/github_repo/model/search_settings_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SearchSettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchSettingsRepository extends _i1.Mock
    implements _i2.SearchSettingsRepository {
  MockSearchSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SearchSettingsSort get sort => (super.noSuchMethod(
        Invocation.getter(#sort),
        returnValue: _i3.SearchSettingsSort.bestMatch,
      ) as _i3.SearchSettingsSort);
  @override
  _i3.SearchSettingsOrder get order => (super.noSuchMethod(
        Invocation.getter(#order),
        returnValue: _i3.SearchSettingsOrder.desc,
      ) as _i3.SearchSettingsOrder);
  @override
  _i4.Future<void> setSort(_i3.SearchSettingsSort? sort) => (super.noSuchMethod(
        Invocation.method(
          #setSort,
          [sort],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> setOrder(_i3.SearchSettingsOrder? order) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOrder,
          [order],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
